// Code generated by go-bindata. DO NOT EDIT.
// source: ui/dist/css/app.bdcc59ce.css
package bindata


import (
	"os"
	"time"
)

var _bindataUiDistCssAppbdcc59cecss = []byte(
	"\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x04\xc0\xc1\x0a\xc2\x30\x0c\x00\xd0\x8f\x19\xde\x5a\xa9\x8a\x1e\xba\xd3" +
	"\x6e\xfe\x46\xa8\xa9\x0b\x74\x4d\x48\xc2\x54\x46\xff\xdd\x37\x81\xc8\x51\xb9\x7b\xac\xb0\x51\xfb\xe5\x65\xc7\x4e" +
	"\x1a\x9e\xd8\x76\x74\x2a\x10\x16\x25\x68\xc1\xa0\x5b\x34\x54\xaa\x73\xe1\xc6\x9a\xa7\x6b\xb9\xe1\x3d\xcd\x1b\xe8" +
	"\x9b\x7a\x74\x96\xfc\x48\xf2\x1d\x67\x2c\x2b\xa8\xdb\xf1\xa1\x97\xaf\xf9\x92\xd2\x69\xfc\x03\x00\x00\xff\xff\x02" +
	"\x8f\xcb\xed\x65\x00\x00\x00")

func bindataUiDistCssAppbdcc59cecssBytes() ([]byte, error) {
	return bindataRead(
		_bindataUiDistCssAppbdcc59cecss,
		"ui/dist/css/app.bdcc59ce.css",
	)
}



func bindataUiDistCssAppbdcc59cecss() (*asset, error) {
	bytes, err := bindataUiDistCssAppbdcc59cecssBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{
		name: "ui/dist/css/app.bdcc59ce.css",
		size: 101,
		md5checksum: "",
		mode: os.FileMode(420),
		modTime: time.Unix(1588942021, 0),
	}

	a := &asset{bytes: bytes, info: info}

	return a, nil
}

